"""Agent registry and slash command rendering."""

from __future__ import annotations

from pathlib import Path

AGENT_REGISTRY: dict[str, dict] = {
    "claude": {"dir": ".claude", "subdir": "commands", "format": "md", "args": "$ARGUMENTS"},
    "cursor": {"dir": ".cursor", "subdir": "commands", "format": "md", "args": "$ARGUMENTS"},
    "windsurf": {"dir": ".windsurf", "subdir": "workflows", "format": "md", "args": "$ARGUMENTS"},
    "copilot": {"dir": ".copilot", "subdir": "agents", "format": "agent.md", "args": "$ARGUMENTS"},
    "codex": {"dir": ".codex", "subdir": "skills", "format": "skill.md", "args": "$ARGUMENTS"},
    "gemini": {"dir": ".gemini", "subdir": "commands", "format": "toml", "args": "{{args}}"},
    "kilocode": {"dir": ".config/kilo", "subdir": "commands", "format": "md", "args": "$ARGUMENTS"},
    "junie": {"dir": ".junie", "subdir": "commands", "format": "md", "args": "$ARGUMENTS"},
}

# Full slash command templates matching the spec in reference-templates.md

COMMANDS = {
    "kluris": {
        "description": "Read, write, and search the Kluris brain — your team's shared knowledge base",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
{args}

## What is Kluris?

A Kluris brain is a shared knowledge base -- a standalone git repo of structured
markdown. You are the team's subject matter expert.

**Config:** `~/.kluris/config.yml` (or `KLURIS_CONFIG` env var).

If no config or no brains: tell user to run `pipx install kluris && kluris create`.

## Reading protocol

1. **Read config** -- find brains. Use `default_brain` if set.
2. **Read brain.md** -- see the description (what this brain covers) and root lobes.
3. **Pick relevant lobes** -- read their `map.md` (at most 3 lobes).
4. **Drill deeper** -- if a map.md shows sub-lobes, follow the relevant one.
5. **Read neurons** -- the specific files that match (at most 10).
6. **Follow synapses** -- check `related:` links for connected knowledge.
7. **Check glossary.md** -- for domain-specific terms.

## Writing rules

- Create or update `.md` files with YAML frontmatter: `parent`, `related`, `tags`, `created`, `updated`
- Do NOT edit `map.md` or `brain.md` -- auto-generated by `kluris dream`
- Bidirectional synapses: if A links to B, add the reverse link in B
- Focus on decisions and rationale, not just descriptions
- After writing, remind the user to run `/kluris.push`

## Handle the request

- **find/read** -- navigate the brain, summarize findings
- **store/remember** -- create or update neurons in the right lobe
- **work on a task** -- read relevant knowledge first, then proceed
- **learn from a project** -- analyze codebase, populate the brain
- **validate** -- check links, suggest synapses, flag stale content
- If unclear, ask
""",
    },
    "kluris.think": {
        "description": "Load brain knowledge, then work on the task as the team's expert",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
Task: {args}

Config: `~/.kluris/config.yml` (or `KLURIS_CONFIG` env var).

## Your role

You are the team's subject matter expert. Internalize the brain's knowledge
and apply it with judgment.

## Read the brain

Follow the reading protocol: config -> brain.md (description + lobes) ->
relevant map.md files -> neurons (max 10) -> follow synapses -> glossary.

## Act as the expert

- Apply documented conventions as second nature
- Respect architectural decisions and their rationale
- If the task contradicts a documented decision, flag the conflict
- Prefer approaches consistent with the brain's patterns

If this task produces new knowledge, suggest `/kluris.remember`.
""",
    },
    "kluris.remember": {
        "description": "Extract and store knowledge in the brain — from session or a specific topic",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
{args}

Config: Read `~/.kluris/config.yml` (or `KLURIS_CONFIG` env var).
Select the relevant brain. Use `default_brain` if set.

## Mode

**If arguments were provided:** Analyze what was specified and extract key
knowledge worth persisting.

**If no arguments were provided:** Review the current session. Identify
decisions made, patterns established, problems solved, architecture
discussed, or any knowledge valuable in future sessions.

## Process

1. **Read brain.md to see root lobes, then read relevant map.md files
2. **Read brain.md** to understand the lobe structure
3. Analyze — either the specified topic or the session context
4. Extract knowledge. Focus on:
   - Decisions and their rationale ("we chose X because Y")
   - Architectural patterns worth reusing
   - Gotchas and solutions to non-obvious problems
   - Standards or conventions established
   - Infrastructure or config details easy to forget
5. Classify — decide which lobe(s) this belongs to
6. Write — create or update neurons with proper frontmatter:
   ```yaml
   ---
   parent: <relative path to parent map.md>
   related: []
   tags: []
   created: <today>
   updated: <today>
   ---
   ```
7. When adding `related:` links, add the reverse link too (bidirectional)
8. Skip low-value noise — don't store trivial fixes or code-obvious things
9. Do NOT edit map.md or brain.md — auto-generated
10. Report what you stored and where
11. Remind the user to run `/kluris.push` when ready to commit
""",
    },
    "kluris.learn": {
        "description": "Learn a specific aspect of the project and store it in the brain",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
{args}

Config: `~/.kluris/config.yml` (or `KLURIS_CONFIG` env var).

## What to learn

You MUST have a focus. If no arguments were provided, ask the user:
"What should I learn? Examples: API endpoints, database schema, auth flow,
architecture, deployment setup"

Do NOT scan the entire project. Focus on the specific topic the user asked for.

Examples:
- `/kluris.learn API endpoints` -- extract routes, methods, request/response
- `/kluris.learn database schema` -- tables, relationships, migrations
- `/kluris.learn auth flow` -- authentication, authorization, token handling
- `/kluris.learn deployment` -- Docker, CI/CD, environments
- `/kluris.learn tech stack overview` -- languages, frameworks, dependencies

## Step 1: Check what exists

Read brain.md for lobes. Check if neurons about this topic already exist.
**Never overwrite existing neurons.** Skip what's already documented.

## Step 2: Analyze only the relevant parts

Only read files related to the focus topic. Don't scan the entire project.

## Step 3: Present a plan BEFORE writing

Tell the user what you found and what you'll create:

> Found 12 API endpoints in btb-backend-core.
> I'll create in services/btb-backend-core/endpoints/:
> - post-auth-login.md
> - get-users-me.md
> - ...
>
> Proceed?

**Wait for approval before writing.**

## Step 4: Write neurons (after approval)

- Default location: `services/<project-name>/`
- Focus on decisions and rationale
- For APIs: method, path, request body, response, auth requirements
- Frontmatter: parent, related, tags, created, updated
- Do NOT edit map.md or brain.md

## Step 5: Remind user to run `kluris dream` and `/kluris.push`
""",
    },
    "kluris.recall": {
        "description": "Search the brain and summarize what it knows about a topic (read-only)",
        "allowed_tools": "Read, Bash(grep:*), Bash(find:*), Bash(cd:*), Glob, Grep",
        "body": """\
Search the brain for: {args}

Config: Read `~/.kluris/config.yml` (or `KLURIS_CONFIG` env var).

## Steps

1. **Read brain.md for lobes, then search relevant map.md files for matching neurons
2. Search all brains: `grep -ri "{args}" <brain_path>/ --include="*.md" -l`
3. Read the top matching neurons (max 10)
4. Follow their `related:` synapses for additional context
5. Check `<brain_path>/glossary.md` for relevant domain terms
6. Summarize findings with links to source files
7. If no results, try broader terms or read brain.md for related lobes
""",
    },
    "kluris.push": {
        "description": "Commit and push all pending Kluris brain changes to git",
        "allowed_tools": "Bash(cd:*), Bash(git:*)",
        "body": """\
Config: Read `~/.kluris/config.yml` (or `KLURIS_CONFIG` env var).

## Push the brain

1. Check for changes:
   ```bash
   cd <brain_path> && git status --short
   ```
2. If no changes, say "Brain is already up to date — nothing to push."
3. Show a summary of what changed (files added/modified/deleted)
4. Stage everything:
   ```bash
   cd <brain_path> && git add -A
   ```
5. Commit with a descriptive message:
   ```bash
   cd <brain_path> && git commit -m "<commit_prefix> {args}"
   ```
   If no arguments provided, generate a commit message from changed files.
6. Push:
   ```bash
   cd <brain_path> && git push origin <branch>
   ```
7. Confirm: "Brain pushed — N files committed and pushed to <branch>."
""",
    },
    "kluris.dream": {
        "description": "Kluris brain maintenance — validate, repair, and strengthen the knowledge base",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
Config: Read `~/.kluris/config.yml` (or `KLURIS_CONFIG` env var).
Select the relevant brain. Use `default_brain` if set.

Focus on: {args}
(If no focus specified, do a full brain maintenance sweep.)

## The brain is dreaming — consolidation and repair

### Phase 1: Structural integrity

1. Read `<brain_path>/brain.md` and every map.md to understand full structure
2. **Broken synapses**: Find all markdown links in every neuron and map, check
   each target exists. List broken links with file and line.
3. **Orphaned neurons**: Find all .md files NOT referenced from any map.md or
   other neuron. List them.
4. **Map freshness**: Compare map.md contents against actual files. Report
   neurons on disk but not in their map.

### Phase 2: Frontmatter health

5. Check every neuron's YAML frontmatter:
   - Missing `parent:` — suggest correct parent map.md
   - Missing `created:` — suggest from git log
   - Empty `tags:` — suggest tags based on content

### Phase 3: Smart synapse discovery

6. **Bidirectional check**: For every neuron with `related:` entries, verify
   the target also lists the source. Report one-way synapses with fix.
7. For each neuron, scan content for references to topics in OTHER neurons.
   Suggest `related:` entries (bidirectional) and inline links.
8. Look for overlapping topics that could benefit from cross-linking or merging.

### Phase 4: Staleness check

9. Check `updated:` dates on all neurons. Flag any not updated in 90+ days.
10. For stale neurons, read them and assess: is the content likely still accurate?

### Phase 5: Report

Present a brain health report:
- **Broken synapses**: N found (with fix suggestions)
- **One-way synapses**: N found (with bidirectional fix suggestions)
- **Orphaned neurons**: N found (with suggested lobe placement)
- **Frontmatter issues**: N neurons with missing fields (with fixes)
- **Suggested new synapses**: N potential connections (list pairs)
- **Stale neurons**: N potentially outdated (with recommendations)

Ask: "Want me to fix the structural issues?"

**Important:** Do NOT auto-fix without asking. Present the report, let the
user decide. If they approve, make fixes but do NOT commit — remind them
to run `/kluris.push`.

### Tip: Run the CLI for mechanical fixes

For regenerating maps and brain.md, tell the user to run
the CLI command in their terminal:

```bash
kluris dream
```

The CLI `kluris dream` mechanically regenerates all map.md files and the
brain.md root index. This slash command (`/kluris.dream`) adds AI-powered
analysis on top — synapse suggestions, staleness checks, content quality.
Use both: CLI for mechanics, slash command for intelligence.
""",
    },
    "kluris.mri": {
        "description": "Generate an interactive visualization of the brain's knowledge graph",
        "allowed_tools": "Bash(kluris:*), Bash(open:*)",
        "body": """\
Config: Read `~/.kluris/config.yml` (or `KLURIS_CONFIG` env var).

## Generate a brain MRI

Run the CLI command to generate the visualization:

```bash
kluris mri
```

This creates `brain-mri.html` in the brain directory -- a standalone HTML file
with an interactive force-directed graph showing all neurons, lobes, and their
connections.

After generating, open it:

```bash
open <brain_path>/brain-mri.html
```

The MRI shows:
- **Nodes** colored by lobe (green = neuron, blue = map, orange = brain.md)
- **Edges** by type (solid = parent, dashed = related/synapse, dotted = inline link)
- **Click** any node to see its path and type
- **Node count and edge count** in the top-left panel

This is a CLI-only operation -- the visualization requires generating HTML
with JavaScript, which the agent cannot do inline.
""",
    },
}


def _render_md(cmd_name: str, cmd: dict, args_placeholder: str,
               copilot: bool = False) -> str:
    """Render a markdown slash command file."""
    body = cmd["body"].replace("{args}", args_placeholder)
    allowed = cmd.get("allowed_tools", "")
    fm = f"---\ndescription: {cmd['description']}\n"
    if copilot:
        fm += f"mode: {cmd_name}\n"
    if allowed:
        fm += f"allowed-tools: {allowed}\n"
    fm += "---\n\n"
    return fm + body + "\n"


def _render_toml(cmd_name: str, cmd: dict, args_placeholder: str) -> str:
    """Render a TOML slash command file."""
    body = cmd["body"].replace("{args}", args_placeholder)
    body = body.replace('"""', '\\"\\"\\"')
    return f'description = "{cmd["description"]}"\n\nprompt = """\n{body}\n"""\n'


def _render_skill_md(cmd_name: str, cmd: dict, args_placeholder: str) -> str:
    """Render a single SKILL.md for one command (spec-kit pattern)."""
    body = cmd["body"].replace("{args}", args_placeholder)
    # Convert kluris.think -> kluris-think for directory name
    skill_name = cmd_name.replace(".", "-")
    frontmatter = (
        "---\n"
        f"name: {skill_name}\n"
        f"description: {cmd['description']}\n"
        "---\n\n"
    )
    return frontmatter + f"# {cmd['description']}\n\n{body}\n"


def render_commands(agent_name: str, output_dir: Path) -> list[Path]:
    """Render all slash command files for an agent into output_dir."""
    reg = AGENT_REGISTRY[agent_name]
    fmt = reg["format"]
    args = reg["args"]
    output_dir.mkdir(parents=True, exist_ok=True)
    files = []

    if fmt == "skill.md":
        # Codex: one SKILL.md per command in separate directories (spec-kit pattern)
        for name, cmd in COMMANDS.items():
            skill_name = name.replace(".", "-")
            skill_dir = output_dir / skill_name
            skill_dir.mkdir(parents=True, exist_ok=True)
            content = _render_skill_md(name, cmd, args)
            path = skill_dir / "SKILL.md"
            path.write_text(content, encoding="utf-8")
            files.append(path)
    elif fmt == "toml":
        for name, cmd in COMMANDS.items():
            content = _render_toml(name, cmd, args)
            path = output_dir / f"{name}.toml"
            path.write_text(content, encoding="utf-8")
            files.append(path)
    elif fmt == "agent.md":
        for name, cmd in COMMANDS.items():
            content = _render_md(name, cmd, args, copilot=True)
            path = output_dir / f"{name}.agent.md"
            path.write_text(content, encoding="utf-8")
            files.append(path)
    else:
        for name, cmd in COMMANDS.items():
            content = _render_md(name, cmd, args)
            path = output_dir / f"{name}.md"
            path.write_text(content, encoding="utf-8")
            files.append(path)

    return files


def install_for_agent(agent_name: str, home: Path | None = None) -> list[Path]:
    """Install slash commands for a specific agent at the correct home path."""
    reg = AGENT_REGISTRY[agent_name]
    base = (home or Path.home()) / reg["dir"] / reg["subdir"]
    return render_commands(agent_name, base)
