"""Agent registry and skill rendering (Agent Skills standard)."""

from __future__ import annotations

from pathlib import Path

# All agents now use SKILL.md in their skills directory
AGENT_REGISTRY: dict[str, dict] = {
    "claude": {"dir": ".claude", "subdir": "skills"},
    "cursor": {"dir": ".cursor", "subdir": "skills"},
    "windsurf": {"dir": ".codeium/windsurf", "subdir": "skills",
                  "also_workflow": ".codeium/windsurf/global_workflows"},
    "copilot": {"dir": ".copilot", "subdir": "skills"},
    "codex": {"dir": ".codex", "subdir": "skills"},
    "gemini": {"dir": ".gemini", "subdir": "skills"},
    "kilocode": {"dir": ".kilo", "subdir": "skills"},
    "junie": {"dir": ".junie", "subdir": "skills"},
}

# Old command directories to clean up during install
OLD_COMMAND_DIRS: dict[str, list[str]] = {
    "claude": [".claude/commands"],
    "cursor": [".cursor/commands"],
    "windsurf": [".codeium/windsurf/global_workflows", ".windsurf/workflows"],
    "copilot": [".copilot/agents"],
    "codex": [".agents/skills"],
    "gemini": [".gemini/commands"],
    "kilocode": [".config/kilo/commands", ".kilocode/commands"],
    "junie": [".junie/commands"],
}

SKILL_DESCRIPTION = """\
Your team's shared AI brain -- a git-backed knowledge base of architecture \
decisions, service docs, API specs, conventions, and learnings. Use this \
skill whenever the user mentions: brain, team knowledge, "what do we know \
about", architecture decisions, service documentation, API endpoints, \
coding standards, deployment docs, "remember this", "store this decision", \
or wants to recall, learn, document, or work with shared project knowledge. \
Also trigger when the user asks about how services work, why decisions \
were made, or needs context from other projects. The brain paths are \
baked in below -- do not search for config files."""

SKILL_BODY = """\
{brain_info}

## You are the team's subject matter expert

The brain is a SEPARATE git repo at the path shown above. The current
directory is the PROJECT you're working in.
- ANALYZE the current project
- WRITE to the brain directory
- Never create brain.md, map.md, or kluris.yml in the current project

## Reading protocol

1. Read `<brain_path>/brain.md` -- see description and root lobes
2. Pick relevant lobes -- read their `map.md` (max 3)
3. Drill into sub-lobes if needed
4. Read specific neurons (max 10)
5. Follow `related:` synapses for connected knowledge
6. Check `glossary.md` for domain terms

## Intent detection

Understand the user's intent from their message:

**Search** -- "what do we know about X", "find info about Y"
Navigate the brain, read neurons, summarize findings. Read-only.

**Think** -- "implement X", "work on Y using brain knowledge"
Read the brain first, then work on the task. Apply documented conventions.
If the task contradicts a documented decision, flag the conflict.

**Learn from project** -- "learn the endpoints", "document the schema"
Analyze the CURRENT PROJECT, write to the BRAIN.
Present a plan before writing. Wait for approval.
Default location: `<brain_path>/services/<project-name>/`
Never overwrite existing neurons.
If user asks for OpenAPI: generate `openapi.yml` (OpenAPI 3.1), not markdown.

**Remember** -- "remember we chose X", "store that we decided Y"
Write a specific piece of knowledge to the brain.
Find the right lobe, check for existing neurons, ask before writing.

**Create neuron** -- "create a decision record about X"
Templates: decision (Context, Decision, Rationale, Alternatives, Consequences),
incident (Summary, Timeline, Root cause, Impact, Resolution, Lessons learned),
runbook (Purpose, Prerequisites, Steps, Rollback, Contacts).

**Create lobe** -- "create a new section for monitoring"
Create directory in brain. Remind user to run `kluris dream`.

## Writing rules

- Frontmatter on every neuron: parent, related, tags, created, updated
- Bidirectional synapses: if A links to B, add reverse link in B
- Focus on decisions and rationale, not just descriptions
- Do NOT edit map.md or brain.md -- auto-generated by `kluris dream`
- After writing, remind user to run `kluris dream` then `kluris push`

## CLI commands (for mechanical operations)

These are terminal commands, not skill actions:
- `kluris dream` -- regenerate maps, validate links
- `kluris push` -- commit and push brain changes to git
- `kluris mri` -- generate interactive visualization
- `kluris templates` -- list neuron templates
"""


# Single COMMANDS dict for backward compat with render_commands
COMMANDS = {
    "kluris": {
        "description": SKILL_DESCRIPTION,
        "body": SKILL_BODY,
    },
}


def render_skill(brain_info: str = "") -> str:
    """Render the kluris SKILL.md content."""
    body = SKILL_BODY.replace("{brain_info}", brain_info)
    desc = SKILL_DESCRIPTION.replace('"', '\\"')
    return (
        "---\n"
        f"name: kluris\n"
        f'description: "{desc}"\n'
        "---\n\n"
        f"{body}\n"
    )


def _render_workflow(brain_info: str = "") -> str:
    """Render a Windsurf workflow .md file (for /kluris manual invocation)."""
    body = SKILL_BODY.replace("{brain_info}", brain_info)
    desc = SKILL_DESCRIPTION[:200].replace('"', '\\"')
    return (
        f"---\n"
        f'description: "{desc}"\n'
        f"---\n\n"
        f"{body}\n"
    )


def render_commands(agent_name: str, output_dir: Path, brain_info: str = "") -> list[Path]:
    """Install kluris SKILL.md for an agent."""
    skill_dir = output_dir / "kluris"
    skill_dir.mkdir(parents=True, exist_ok=True)
    content = render_skill(brain_info)
    path = skill_dir / "SKILL.md"
    path.write_text(content, encoding="utf-8")
    return [path]


def install_workflow(workflow_dir: Path, brain_info: str = "") -> Path:
    """Install a Windsurf workflow .md for /kluris manual invocation."""
    workflow_dir.mkdir(parents=True, exist_ok=True)
    wf_file = workflow_dir / "kluris.md"
    wf_file.write_text(_render_workflow(brain_info), encoding="utf-8")
    return wf_file


def install_for_agent(agent_name: str, home: Path | None = None) -> list[Path]:
    """Install kluris skill for a specific agent at the correct home path."""
    reg = AGENT_REGISTRY[agent_name]
    base = (home or Path.home()) / reg["dir"] / reg["subdir"]
    return render_commands(agent_name, base)
