"""Agent registry and slash command rendering."""

from __future__ import annotations

from pathlib import Path

AGENT_REGISTRY: dict[str, dict] = {
    "claude": {"dir": ".claude", "subdir": "commands", "format": "md", "args": "$ARGUMENTS"},
    "cursor": {"dir": ".cursor", "subdir": "commands", "format": "md", "args": "$ARGUMENTS"},
    "windsurf": {"dir": ".windsurf", "subdir": "workflows", "format": "md", "args": "$ARGUMENTS"},
    "copilot": {"dir": ".copilot", "subdir": "agents", "format": "agent.md", "args": "$ARGUMENTS"},
    "codex": {"dir": ".codex", "subdir": "skills", "format": "skill.md", "args": "$ARGUMENTS"},
    "gemini": {"dir": ".gemini", "subdir": "commands", "format": "toml", "args": "{{args}}"},
    "kilocode": {"dir": ".config/kilo", "subdir": "commands", "format": "md", "args": "$ARGUMENTS"},
    "junie": {"dir": ".junie", "subdir": "commands", "format": "md", "args": "$ARGUMENTS"},
}

# Full slash command templates matching the spec in reference-templates.md

COMMANDS = {
    "kluris": {
        "description": "Read, write, and search the Kluris brain — your team's shared knowledge base",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
{args}

## What is Kluris?

A Kluris brain is a shared knowledge base — a standalone git repo of structured
markdown files. You are the team's subject matter expert. The brain contains
everything the team knows.

**Config:** Read `~/.config/kluris/config.yml` (or the path in env var
`KLURIS_CONFIG`) to discover all available brains.

## First-run detection

If the config file doesn't exist or has no brains registered:

> No brains found. To get started:
> 1. Install kluris: `pipx install kluris`
> 2. Create a brain: `kluris create my-brain`
> 3. Populate it: run `/kluris.learn` in any project
>
> This will create a shared knowledge base your AI agents can read and write.

Stop here — do not proceed until a brain exists.

## Step 1: Discover brains

Read the config file. It lists all available brains with their paths,
descriptions, and types. If there is a `default_brain` set, use it unless
the request clearly targets a different brain. If ambiguous, ask.

## Step 2: Navigate the brain (reading protocol)

Follow this protocol every time you read from the brain. Do not skip steps.

1. **Scan brain.md — read `<brain_path>/brain.md` for lobes and neuron index
   of all neurons with their titles, lobes, tags, and update dates
2. **Start at brain.md** — read `<brain_path>/brain.md` to see all lobes
3. **Descend to relevant lobes** — read the `map.md` of lobes related to
   the request (at most 3)
4. **Read target neurons** — read the specific neurons that match (at most 10)
5. **Follow synapses** — check each neuron's `related:` and inline links;
   read connected neurons for fuller context
6. **Check glossary** — read `<brain_path>/glossary.md` for domain terms

Only after completing this protocol should you answer, summarize, or act.

## Step 3: Read or write

**Reading:** Follow the reading protocol. Present findings with links to
source neurons.

**Writing:** Create or update markdown files in the appropriate lobe. Every
file needs YAML frontmatter:
```yaml
---
parent: <relative path to parent map.md>
related: []
tags: []
created: <today>
updated: <today>
---
```

**Rules:**
- Do NOT edit `map.md` or `brain.md` — auto-generated by
  `kluris dream`
- Use standard markdown links: `[label](./relative/path.md)`
- Focus on decisions and rationale, not just descriptions
- When adding `related:` links, also add the reverse link in the target neuron
  (bidirectional synapses)

## Step 4: Handle the request

- **find/read** — search the brain, read relevant neurons, summarize
- **store/save/remember** — find or create the right neuron, write it
- **update** — find the neuron, update it
- **learn from a project** — analyze the codebase, populate the brain
- **work on a task** — read relevant neurons first, then proceed
- **commit/push** — `cd <brain_path> && git add -A && git commit -m "<prefix> <msg>" && git push origin <branch>`
- **validate/maintain** — check links, orphans, frontmatter, suggest synapses
- If unclear, ask

**Important:** After any write operation, remind the user to run `/kluris.push`
to commit and push. Do NOT run git commands unless explicitly asked.
""",
    },
    "kluris.think": {
        "description": "Load brain knowledge, then work on the task as the team's expert",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
Task: {args}

Config: Read `~/.config/kluris/config.yml` (or `KLURIS_CONFIG` env var).
Select the relevant brain based on context. Use `default_brain` if set.

## Your role

You are the team's subject matter expert. The brain contains everything the
team knows — architecture decisions, conventions, infrastructure details,
past incidents, domain knowledge. You don't just "look things up" — you
internalize the brain's knowledge and apply it with judgment, the way a
senior engineer who's been on the team for years would.

## Step 1: Read the brain (full reading protocol)

1. **Scan brain.md — read `<brain_path>/brain.md` for lobes and neuron index
2. **Start at brain.md** — read `<brain_path>/brain.md` to see all lobes
3. **Descend to relevant lobes** — read `map.md` of related lobes (max 3)
4. **Read target neurons** — read matching neurons (max 10)
5. **Follow synapses** — check `related:` and inline links
6. **Check glossary** — read `<brain_path>/glossary.md` for domain terms

## Step 2: Act as the expert

With the brain's knowledge internalized, work on the task:
- Apply documented conventions and standards as second nature
- Respect architectural decisions and their rationale
- If the task contradicts a documented decision, flag it — explain the
  conflict and the original reasoning before proceeding
- When multiple approaches exist, prefer the one consistent with the
  brain's documented patterns

## Step 3: Suggest remembering

If this task produces new knowledge worth persisting, suggest running
`/kluris.remember`.
""",
    },
    "kluris.remember": {
        "description": "Analyze and extract knowledge to store in the Kluris brain",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
{args}

Config: Read `~/.config/kluris/config.yml` (or `KLURIS_CONFIG` env var).
Select the relevant brain. Use `default_brain` if set.

## Mode

**If arguments were provided:** Analyze what was specified and extract key
knowledge worth persisting.

**If no arguments were provided:** Review the current session. Identify
decisions made, patterns established, problems solved, architecture
discussed, or any knowledge valuable in future sessions.

## Process

1. **Scan brain.md to see lobes and what neurons already exist
2. **Read brain.md** to understand the lobe structure
3. Analyze — either the specified topic or the session context
4. Extract knowledge. Focus on:
   - Decisions and their rationale ("we chose X because Y")
   - Architectural patterns worth reusing
   - Gotchas and solutions to non-obvious problems
   - Standards or conventions established
   - Infrastructure or config details easy to forget
5. Classify — decide which lobe(s) this belongs to
6. Write — create or update neurons with proper frontmatter:
   ```yaml
   ---
   parent: <relative path to parent map.md>
   related: []
   tags: []
   created: <today>
   updated: <today>
   ---
   ```
7. When adding `related:` links, add the reverse link too (bidirectional)
8. Skip low-value noise — don't store trivial fixes or code-obvious things
9. Do NOT edit map.md or brain.md — auto-generated
10. Report what you stored and where
11. Remind the user to run `/kluris.push` when ready to commit
""",
    },
    "kluris.learn": {
        "description": "Analyze the current project and populate the Kluris brain — the fastest way to build team knowledge",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
Analyze this project and populate the brain with what you learn.

Config: Read `~/.config/kluris/config.yml` (or `KLURIS_CONFIG` env var).
Select the relevant brain. Use `default_brain` if set.

Focus on: {args}
(If no focus specified, do a general scan.)

## Why this matters

This is the fastest way to turn a codebase into documented knowledge. After
running this command, every AI agent on your team can answer questions about
this project using the brain — architecture, conventions, deployment, APIs,
everything.

## Step 1: Understand the brain

Read `<brain_path>/brain.md` to see what's
already documented. Don't duplicate existing knowledge.

## Step 2: Analyze the project

Examine systematically:
- README, docs/, documentation files
- Project structure (package.json, pyproject.toml, pom.xml, etc.)
- Key config files (Docker, CI/CD, infrastructure)
- Source code architecture (entry points, modules, routing)
- API contracts (OpenAPI, GraphQL, protobuf)
- Database schemas and migrations
- Environment configuration patterns
- Dependencies and their purposes

## Step 3: Classify into lobes

- **architecture/** — system design, service boundaries, data flow, tech stack
- **product/** — features, user flows, business logic
- **standards/** — coding patterns, naming conventions, error handling
- **services/** — individual services, APIs, ownership, responsibilities
- **infrastructure/** — hosting, CI/CD, Docker, networking, deployment
- **decisions/** — key decisions and their rationale
- **cortex/** — runbooks, playbooks, dev workflows, onboarding
- **wisdom/** — domain expertise, learnings, things figured out

If the right lobe doesn't exist, create the directory (`mkdir -p`) but do NOT
create map.md — remind the user to run `kluris dream` to generate it.

## Step 4: Write neurons

Create or update files with proper frontmatter. Focus on decisions and
rationale.
Good: "We use Keycloak because it supports multi-tenant OIDC out of the box"
Bad: "The project uses Keycloak"

When adding `related:` links, add the reverse link too (bidirectional).

## Step 5: Do NOT edit map.md or brain.md

## Step 6: Report what you documented, organized by lobe

## Step 7: Remind the user to run `/kluris.push` when ready to commit
""",
    },
    "kluris.recall": {
        "description": "Search the brain and summarize what it knows about a topic (read-only)",
        "allowed_tools": "Read, Bash(grep:*), Bash(find:*), Bash(cd:*), Glob, Grep",
        "body": """\
Search the brain for: {args}

Config: Read `~/.config/kluris/config.yml` (or `KLURIS_CONFIG` env var).

## Steps

1. **Scan brain.md first — check the neuron index table for matching titles or tags
2. Search all brains: `grep -ri "{args}" <brain_path>/ --include="*.md" -l`
3. Read the top matching neurons (max 10)
4. Follow their `related:` synapses for additional context
5. Check `<brain_path>/glossary.md` for relevant domain terms
6. Summarize findings with links to source files
7. If no results, try broader terms or read brain.md for related lobes
""",
    },
    "kluris.neuron": {
        "description": "Create a new neuron (knowledge file) in the Kluris brain",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(mkdir:*)",
        "body": """\
Create a new neuron about: {args}

Config: Read `~/.config/kluris/config.yml` (or `KLURIS_CONFIG` env var).
Select the relevant brain. Use `default_brain` if set.

## Steps

1. Read `<brain_path>/brain.md` to find the best lobe for this topic
2. Read `<brain_path>/kluris.yml` to check for `neuron_templates`
3. **Detect template:** If the user specifies a type (e.g., "decision about X",
   "incident: Y") or the context clearly matches a template name, use that
   template. Otherwise, use the default format.
4. Create the neuron with frontmatter:
   ```yaml
   ---
   parent: <relative path to parent map.md>
   template: <template name, if used>
   related: []
   tags: []
   created: <today>
   updated: <today>
   ---
   ```
5. **If using a template:** Generate the section headings from the template's
   `sections` list.
6. Write the content
7. If the right lobe doesn't exist, create the directory (`mkdir -p`) but do
   NOT create map.md — remind the user to run `kluris dream` to generate it
8. Remind the user to run `/kluris.push` when ready to commit
""",
    },
    "kluris.lobe": {
        "description": "Create a new brain region (lobe) in the Kluris brain",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(git:*), Bash(mkdir:*)",
        "body": """\
Create a new brain region: {args}

Config: Read `~/.config/kluris/config.yml` (or `KLURIS_CONFIG` env var).
Select the relevant brain. Use `default_brain` if set.

## Steps

1. Read `<brain_path>/brain.md` to understand the current structure
2. Create the lobe: `mkdir -p <brain_path>/<lobe-path>`
3. Do NOT create map.md — run `kluris dream` to regenerate maps
4. Do NOT edit parent map.md — run `kluris dream` to regenerate
5. Remind the user to run `/kluris.push` when ready to commit
""",
    },
    "kluris.push": {
        "description": "Commit and push all pending Kluris brain changes to git",
        "allowed_tools": "Bash(cd:*), Bash(git:*)",
        "body": """\
Config: Read `~/.config/kluris/config.yml` (or `KLURIS_CONFIG` env var).

## Push the brain

1. Check for changes:
   ```bash
   cd <brain_path> && git status --short
   ```
2. If no changes, say "Brain is already up to date — nothing to push."
3. Show a summary of what changed (files added/modified/deleted)
4. Stage everything:
   ```bash
   cd <brain_path> && git add -A
   ```
5. Commit with a descriptive message:
   ```bash
   cd <brain_path> && git commit -m "<commit_prefix> {args}"
   ```
   If no arguments provided, generate a commit message from changed files.
6. Push:
   ```bash
   cd <brain_path> && git push origin <branch>
   ```
7. Confirm: "Brain pushed — N files committed and pushed to <branch>."
""",
    },
    "kluris.dream": {
        "description": "Kluris brain maintenance — validate, repair, and strengthen the knowledge base",
        "allowed_tools": "Read, Write, Bash(cd:*), Bash(grep:*), Bash(find:*), Glob, Grep",
        "body": """\
Config: Read `~/.config/kluris/config.yml` (or `KLURIS_CONFIG` env var).
Select the relevant brain. Use `default_brain` if set.

Focus on: {args}
(If no focus specified, do a full brain maintenance sweep.)

## The brain is dreaming — consolidation and repair

### Phase 1: Structural integrity

1. Read `<brain_path>/brain.md` and every map.md to understand full structure
2. **Broken synapses**: Find all markdown links in every neuron and map, check
   each target exists. List broken links with file and line.
3. **Orphaned neurons**: Find all .md files NOT referenced from any map.md or
   other neuron. List them.
4. **Map freshness**: Compare map.md contents against actual files. Report
   neurons on disk but not in their map.

### Phase 2: Frontmatter health

5. Check every neuron's YAML frontmatter:
   - Missing `parent:` — suggest correct parent map.md
   - Missing `created:` — suggest from git log
   - Empty `tags:` — suggest tags based on content

### Phase 3: Smart synapse discovery

6. **Bidirectional check**: For every neuron with `related:` entries, verify
   the target also lists the source. Report one-way synapses with fix.
7. For each neuron, scan content for references to topics in OTHER neurons.
   Suggest `related:` entries (bidirectional) and inline links.
8. Look for overlapping topics that could benefit from cross-linking or merging.

### Phase 4: Staleness check

9. Check `updated:` dates on all neurons. Flag any not updated in 90+ days.
10. For stale neurons, read them and assess: is the content likely still accurate?

### Phase 5: Report

Present a brain health report:
- **Broken synapses**: N found (with fix suggestions)
- **One-way synapses**: N found (with bidirectional fix suggestions)
- **Orphaned neurons**: N found (with suggested lobe placement)
- **Frontmatter issues**: N neurons with missing fields (with fixes)
- **Suggested new synapses**: N potential connections (list pairs)
- **Stale neurons**: N potentially outdated (with recommendations)

Ask: "Want me to fix the structural issues?"

**Important:** Do NOT auto-fix without asking. Present the report, let the
user decide. If they approve, make fixes but do NOT commit — remind them
to run `/kluris.push`.

### Tip: Run the CLI for mechanical fixes

For regenerating maps and the neuron index in brain.md, tell the user to run
the CLI command in their terminal:

```bash
kluris dream
```

The CLI `kluris dream` mechanically regenerates all map.md files and the
neuron index in brain.md. This slash command (`/kluris.dream`) adds AI-powered
analysis on top — synapse suggestions, staleness checks, content quality.
Use both: CLI for mechanics, slash command for intelligence.
""",
    },
}


def _render_md(cmd_name: str, cmd: dict, args_placeholder: str,
               copilot: bool = False) -> str:
    """Render a markdown slash command file."""
    body = cmd["body"].replace("{args}", args_placeholder)
    allowed = cmd.get("allowed_tools", "")
    fm = f"---\ndescription: {cmd['description']}\n"
    if copilot:
        fm += f"mode: {cmd_name}\n"
    if allowed:
        fm += f"allowed-tools: {allowed}\n"
    fm += "---\n\n"
    return fm + body + "\n"


def _render_toml(cmd_name: str, cmd: dict, args_placeholder: str) -> str:
    """Render a TOML slash command file."""
    body = cmd["body"].replace("{args}", args_placeholder)
    body = body.replace('"""', '\\"\\"\\"')
    return f'description = "{cmd["description"]}"\n\nprompt = """\n{body}\n"""\n'


def _render_skill_md(cmd_name: str, cmd: dict, args_placeholder: str) -> str:
    """Render a single SKILL.md for one command (spec-kit pattern)."""
    body = cmd["body"].replace("{args}", args_placeholder)
    # Convert kluris.think -> kluris-think for directory name
    skill_name = cmd_name.replace(".", "-")
    frontmatter = (
        "---\n"
        f"name: {skill_name}\n"
        f"description: {cmd['description']}\n"
        "---\n\n"
    )
    return frontmatter + f"# {cmd['description']}\n\n{body}\n"


def render_commands(agent_name: str, output_dir: Path) -> list[Path]:
    """Render all slash command files for an agent into output_dir."""
    reg = AGENT_REGISTRY[agent_name]
    fmt = reg["format"]
    args = reg["args"]
    output_dir.mkdir(parents=True, exist_ok=True)
    files = []

    if fmt == "skill.md":
        # Codex: one SKILL.md per command in separate directories (spec-kit pattern)
        for name, cmd in COMMANDS.items():
            skill_name = name.replace(".", "-")
            skill_dir = output_dir / skill_name
            skill_dir.mkdir(parents=True, exist_ok=True)
            content = _render_skill_md(name, cmd, args)
            path = skill_dir / "SKILL.md"
            path.write_text(content, encoding="utf-8")
            files.append(path)
    elif fmt == "toml":
        for name, cmd in COMMANDS.items():
            content = _render_toml(name, cmd, args)
            path = output_dir / f"{name}.toml"
            path.write_text(content, encoding="utf-8")
            files.append(path)
    elif fmt == "agent.md":
        for name, cmd in COMMANDS.items():
            content = _render_md(name, cmd, args, copilot=True)
            path = output_dir / f"{name}.agent.md"
            path.write_text(content, encoding="utf-8")
            files.append(path)
    else:
        for name, cmd in COMMANDS.items():
            content = _render_md(name, cmd, args)
            path = output_dir / f"{name}.md"
            path.write_text(content, encoding="utf-8")
            files.append(path)

    return files


def install_for_agent(agent_name: str, home: Path | None = None) -> list[Path]:
    """Install slash commands for a specific agent at the correct home path."""
    reg = AGENT_REGISTRY[agent_name]
    base = (home or Path.home()) / reg["dir"] / reg["subdir"]
    return render_commands(agent_name, base)
